# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'fbphotoviewer' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Facebook
  pod 'FBSDKLoginKit'
  pod 'FacebookCore'
  pod 'FacebookLogin'
  
  # Networking
  pod 'SwiftyJSON'
  
  # UI
  pod 'SnapKit', '~> 4.0.0'
  pod 'Closures'
  pod 'Kingfisher'
  pod 'AlisterSwift', :git => 'https://github.com/anodamobi/AlisterSwift.git', :branch => 'develop', :commit => 'ff395f6'
  pod 'DZNEmptyDataSet'
  pod 'PKHUD', '~> 5.0'
  
  # Resources
  pod 'R.swift'

  target 'fbphotoviewerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'fbphotoviewerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
