# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'fbphotoviewer' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Facebook
  pod 'FBSDKLoginKit'
  pod 'FacebookCore'
  pod 'FacebookLogin'
  
  # UI
  pod 'SnapKit', '~> 4.0.0'
  pod 'Closures'
  
  # Resources
  pod 'R.swift'

  target 'fbphotoviewerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'fbphotoviewerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
